config/routes.rb
Rails.application.routes.draw do

  # ルートパスを会員TOPページに設定
  root 'customer/homes#top'
  # 会員TOPページ
  get '/admin' => 'admin/homes#top'
  # 会員紹介ページ
  get '/about' => 'customer/homes#about', as: 'about'


  
  devise_for :customers,skip: :all
  devise_scope :customer do
    #サインアップ
    get 'customers/sign_up' =>'customers/registrations#new', as: :new_customer_registration
    post 'customers'=>'customers/registrations#create', as: :customer_registration
    #ログイン、ログアウト
    get 'customers/sign_in'=>'customers/sessions#new',as: :new_customer_session
    post 'customers/sign_in'=>'customers/sessions#create',as: :customer_session
    delete 'customers/sign_out' =>'customers/sessions#destroy', as: :destroy_customer_session
  end
  
  # 管理者ログイン画面のルーティング
  # セッションパス修正admin→admins
  # devise_for :admins, controllers: {
  #   sessions: 'admins/sessions'
  # }
  
  devise_for :admins,skip: :all
  devise_scope :admin do
    #ログイン、ログアウト
    get 'admins/sign_in'=>'admins/sessions#new',as: :new_admin_session
    post 'admins/sign_in'=>'admins/sessions#create',as: :admin_session
    delete 'admins/sign_out' =>'admins/sessions#destroy', as: :destroy_admin_session
  end
  

  # 管理者側の各機能のルーティング
  # namespaseでURLとコントローラのパスの頭に「/admin」が入るようにする
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :products, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :order_products, only: [:update]
    get '/search' => 'searchs#search', as: 'search'
  end

  # 会員側のルーティング
  # scope moduleでコントローラのパスのみ頭に「/customer」が入るようにする
  scope module: :customer do
    # 今回は他会員の情報を利用しないため、resource(単数形)にすることでURLに:idを含めないようにする
    resource :customers, only: [:show,:edit,:update] do
      # RESTfulなURL以外は個別にcollectionで設定する
      collection do
        # URLとコントローラアクション名が一致しない場合のみ、個別にコントローラのパスを指定する
        get 'withdrawal' => 'customers#withdrawal_show'
        patch 'withdrawal'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      # RESTfulなURL以外は個別にcollectionで設定する
      collection do
        post 'confirm'
        get 'thanks'
      end
    end
    resources :products, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      # RESTfulなURL以外は個別にcollectionで設定する
      collection do
        # URLとコントローラアクション名が一致しない場合のみ、個別にコントローラのパスを指定する
        delete '' => 'cart_items#destroy_all'
      end
    end
    resources :shippings, only: [:index, :edit, :create, :update, :destroy]
    resources :order_products, only: [:update]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable




end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    
    # 多重度の設定
    belongs_to :customer
    belongs_to :product
    
    # バリデーションチェック
    # 空白時、数値以外が入力された場合はエラー
    validates :number, presence: true, numericality: { only_integer: true }
    
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # 多重度の設定
  has_many :shippings,dependent: :destroy
  has_many :cart_items,dependent: :destroy
  has_many :orders,dependent: :destroy
  
  
  # バリデーションチェック

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: /\p{katakana}/}
  validates :first_name_kana, presence: true, format: { with: /\p{katakana}/}
  validates :postcode, presence: true, length: { is: 7 }, format: { with: /\A[0-9]+\z/ }
  validates :address, presence: true
  validates :phone_number, presence: true, format: {with: /\A[0-9]+\z/}
  validates :email, presence: true

  def full_name
    self.last_name + self.first_name
  end

  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end

  
  def active_for_authentication?
   super && (self.is_deleted == false)
  end
  #ログインするときに退会済のユーザーを弾く為のメソッド
  
end

app/models/genre.rb
class Genre < ApplicationRecord
    
    # 多重度の設定
    has_many :products
    
    # バリデーションチェック
    # 空白時にエラー
    validates :name, presence: true

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer, optional: true
  has_many :order_products, dependent: :destroy

  #カラムとして存在しないものをメソッドとして定義する
  attr_accessor :shipping_id

  # バリデーション
  validates :postcode, presence: true, length: { is: 7 }, format: { with: /\A[0-9]+\z/ }
  validates :address, presence: true
  validates :name, presence: true


  # ENUMの設定
  enum pay_method: { "クレジットカード": 0, "銀行振込": 1 }
  enum order_status: {"入金待ち":0, "入金確認":1, "製作中":2, "発送準備中":3, "発送済み":4 }

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord

    # 多重度の設定
    belongs_to :order
	  belongs_to :product
	
	  # 列挙型変数の定義
	  enum production_status: {"着手不可": 0,"製作待ち": 1,"製作中": 2,"製作完了": 3}
  
    # 小計を算出するメソッド
    def subtotal_price
      tax_price * number
    end
    
end

app/models/product.rb
class Product < ApplicationRecord
  
  # 多重度の設定
  belongs_to :genre, optional: true  
  has_many :cart_items
  has_many :order_products
  
 
  # 画像を設定できるようにする
  attachment :image, destroy: false
  
  # バリデーションチェック
  # 空白時にエラー
  validates :name, :explanation, :genre_id, :after_tax_price, :image, presence: true
  # 数値以外が入力された場合はエラー
  validates :after_tax_price, numericality: { only_integer: true }
  # is_saleの値がtrue,false以外の場合はエラー
  validates :is_sale, inclusion: [true, false]
  
  # 商品の税込価格の計算メソッド
  def tax_included
  	(after_tax_price * 1.1).round
  end
    
end

app/models/shipping.rb
class Shipping < ApplicationRecord

  belongs_to :customer

  validates :postcode, presence: true, length: { is: 7 }, format: { with: /\A[0-9]+\z/ }
	validates :address, presence: true
  validates :name, presence: true

  def full_address
    self.postcode + " " + self.address +  " " + self.name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  
 
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/searchs_helper.rb
module Admin::SearchsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/ordres_helper.rb
module Customer::OrdresHelper
end

app/helpers/customer/products_helper.rb
module Customer::ProductsHelper
end

app/helpers/customer/shippings_helper.rb
module Customer::ShippingsHelper
end

app/views/admin/_admin_header.html.erb
<header class="navbar navbar-default">
  <div class="container">
    <nav class='nav navbar-nav navbar-left' >
      <%= link_to admin_path do %>
        <%= image_tag "nagano_cake_logo.png", :size => '100x60' %>
      <% end %>
      <!--<font size="5"><strong>Suits_ec</strong></font>-->
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if admin_signed_in? %>
          <li><%= link_to ' 商品一覧', admin_products_path, class: 'btn btn-info admin-login-header-link' %></li>
          <li><%= link_to ' 会員一覧', admin_customers_path, class: 'btn btn-info admin-login-header-link'  %></li>
          <li><%= link_to ' 注文履歴一覧', admin_orders_path, class: 'btn btn-info admin-login-header-link' %></li>
          <li><%= link_to ' ジャンル一覧', admin_genres_path, class: 'btn btn-info admin-login-header-link' %></li>
          <li><%= link_to ' ログアウト', destroy_admin_session_path, method: :delete, class: 'btn btn-info admin-login-header-link'  %></li><br>
          <div class="pull-right row">
            <%= form_with url: admin_search_path, method: :get, class: "form-inline", local: true do |f| %>
              <div class="col-sm-4">
                <%= f.select :model, [["会員検索","Customer"],["商品検索","Product"],["ジャンル検索","Genre"]], {}, {class: "form-control input-sm"} %>
              </div>
              <div class="col-sm-8">
                <%= f.text_field :content, :placeholder => "Search", class:"search-bar col-sm-4 form-control input-sm" %>
                <%= f.button :type => "submit", style: 'border-style: none;', class:"btn search-btn" do %>
                  <i class='fas fa-search'></i>
                <% end %>
                
              </div>
                
              </div>
            <% end %>
          </div>
          
        <% else %>
          <li><%= link_to ' About', about_path, class: 'btn btn-info'  %></li>
          <li><%= link_to ' 商品一覧', products_path, class: 'btn btn-info'  %></li>
          <li><%= link_to ' 新規登録', new_customer_registration_path, class: 'btn btn-info'  %></li>
          <li><%= link_to ' ログイン', new_admin_session_path, class: 'btn btn-info' %></li>
        <% end %>
      </ul>
        
    </nav>
  </div>
</header>