config/routes.rb
Rails.application.routes.draw do

  # ルートパスを会員TOPページに設定
  root 'customer/homes#top'
  # 会員TOPページ
  get '/admin' => 'admin/homes#top'
  # 会員紹介ページ
  get '/about' => 'customer/homes#about', as: 'about'


  
  devise_for :customers,skip: :all
  devise_scope :customer do
    #サインアップ
    get 'customers/sign_up' =>'customers/registrations#new', as: :new_customer_registration
    post 'customers'=>'customers/registrations#create', as: :customer_registration
    #ログイン、ログアウト
    get 'customers/sign_in'=>'customers/sessions#new',as: :new_customer_session
    post 'customers/sign_in'=>'customers/sessions#create',as: :customer_session
    delete 'customers/sign_out' =>'customers/sessions#destroy', as: :destroy_customer_session
  end
  
  # 管理者ログイン画面のルーティング
  # セッションパス修正admin→admins
  # devise_for :admins, controllers: {
  #   sessions: 'admins/sessions'
  # }
  
  devise_for :admins,skip: :all
  devise_scope :admin do
    #ログイン、ログアウト
    get 'admins/sign_in'=>'admins/sessions#new',as: :new_admin_session
    post 'admins/sign_in'=>'admins/sessions#create',as: :admin_session
    delete 'admins/sign_out' =>'admins/sessions#destroy', as: :destroy_admin_session
  end
  

  # 管理者側の各機能のルーティング
  # namespaseでURLとコントローラのパスの頭に「/admin」が入るようにする
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :products, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :order_products, only: [:update]
    get '/search' => 'searchs#search', as: 'search'
  end

  # 会員側のルーティング
  # scope moduleでコントローラのパスのみ頭に「/customer」が入るようにする
  scope module: :customer do
    # 今回は他会員の情報を利用しないため、resource(単数形)にすることでURLに:idを含めないようにする
    resource :customers, only: [:show,:edit,:update] do
      # RESTfulなURL以外は個別にcollectionで設定する
      collection do
        # URLとコントローラアクション名が一致しない場合のみ、個別にコントローラのパスを指定する
        get 'withdrawal' => 'customers#withdrawal_show'
        patch 'withdrawal'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      # RESTfulなURL以外は個別にcollectionで設定する
      collection do
        post 'confirm'
        get 'thanks'
      end
    end
    resources :products, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      # RESTfulなURL以外は個別にcollectionで設定する
      collection do
        # URLとコントローラアクション名が一致しない場合のみ、個別にコントローラのパスを指定する
        delete '' => 'cart_items#destroy_all'
      end
    end
    resources :shippings, only: [:index, :edit, :create, :update, :destroy]
    resources :order_products, only: [:update]
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  # ログイン中の管理者のみアクセス許可
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
      flash[:notice] = "会員情報を変更しました。"
    else
      render 'edit'
    end

  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number, :email, :is_deleted )
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    
    # ログイン中の管理者のみアクセス許可
    before_action :authenticate_admin!
    
    def index
        if params[:only_today_flag]
            now = Time.current
            # 本日の注文情報のみ取得
            @orders = Order.where(created_at: now.all_day).page(params[:page]).per(10)
            
        elsif params[:customer_id]
            # 指定のユーザーの注文情報のみ取得
            @orders = Order.where(customer_id: params[:customer_id]).page(params[:page]).per(10)
            
        else
            # 全注文情報を取得する
            @orders = Order.all.page(params[:page]).per(10)
        end
    end
    
    def show
        # 指定の注文を取得
        @order = Order.find(params[:id])
    end
    
    def update
        # 指定の注文を取得
        @order = Order.find(params[:id])
        if @order.update(order_params)
            
            # 注文ステータスが「入金確認」となった場合、注文商品の製作ステータスを全て「製作待ち」にする
            if (@order.order_status == "入金確認")
                @order.order_products.each do |order_product|
                    order_product.update(production_status: "製作待ち")
                end
            end
            
            flash[:notice] = "注文ステータスを変更しました。"
            redirect_to admin_order_path(@order)
        else
            render :show
        end
    end
    
    # ストロングパラメータ
    private
	def order_params
		  params.require(:order).permit(:order_status)
	end
    
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
    
    # ログインユーザのみアクセス許可
    before_action :authenticate_customer!
    
    
    def index
        @cart_items = current_customer.cart_items
        @total_price = 0
        @cart_items.each do |cart_item|
            @total_price += cart_item.product.tax_included * cart_item.number
        end
    end
    
    def create
        @cart_item = CartItem.new(cart_item_params)
        @cart_items = current_customer.cart_items
        @duplicate_cart_item = @cart_items.find_by(product: @cart_item.product)
        if @duplicate_cart_item.present?
            @duplicate_cart_item.number += @cart_item.number
            @duplicate_cart_item.save
        else
            @cart_item.save
        end
        redirect_to cart_items_path   
    end
    
    def update
        # IDに基づく商品を取得
        @cart_item = CartItem.find(params[:id])
        if @cart_item.update(cart_item_params)
            flash[:notice] = "数量を変更しました。"
            redirect_to cart_items_path
        else
            @cart_items = current_customer.cart_items
            render :index
        end
    end
    
    def destroy
        @cart_item = CartItem.find(params[:id])
        @cart_item.destroy
        flash[:notice] = "商品をカートから削除しました。"
        redirect_to cart_items_path
    end
    
    def destroy_all
        @cart_items = current_customer.cart_items
        @cart_items.destroy_all
        flash[:notice] = "カート内の商品を全て削除しました。"
        redirect_to cart_items_path
    end
    
    private
    # ストロングパラメータ
    def cart_item_params
        params.require(:cart_item).permit(:customer_id, :product_id, :number)
    end
    
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  
  # ログイン中のユーザのみアクセス許可
  before_action :authenticate_customer!

  def show
   @customer = current_customer
  end

  def update
    @customer = Customer.find(current_customer.id)
    if @customer.update(customer_params)
      flash[:notice] = "会員情報を更新しました。"
       redirect_to customers_path(@customer)
    else
       render "edit"
    end
  end

  def edit
      @customer = Customer.find(current_customer.id)
  end

  def withdrawal
    @customer = Customer.find(current_customer.id)
    @customer.update(is_deleted: true)
    # ログイン、ユーザーを弾く
    reset_session
    #登録情報の消去メソッド
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:postcode,:email,:address,:phone_number)
  end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController

  def top
    # ジャンルが有効である商品の中からランダムで4つ取得する
    @products = Product.eager_load(:genre).where(genres: {is_active: true}).order("RANDOM()").limit(4)
    # 有効ジャンルを全て取得
    @genres = Genre.where(is_active: true).all
  end

  def about
  end
  
  
  
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/order_products_controller.rb
class Customer::OrderProductsController < ApplicationController
    
    # ログイン中のユーザのみアクセス許可
    before_action :authenticate_customer!
    
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController

  # ログイン中のユーザのみアクセス許可
  before_action :authenticate_customer!

  def new
    # 表示用
    @customer = current_customer
    # 新規注文用の箱
    @order = Order.new(customer_id: @customer.id)
    # 自分のIDの配送先を全部とってくる
    @shippings = Shipping.where(customer_id: @customer.id)
  end

  def confirm
    # 新規注文用の箱
    @order = Order.new(order_params)
    # 表示用
    @customer = current_customer
    # カートの中身をインスタンス変数に入れる
    @items = @customer.cart_items
    # 自分のIDの配送先を全部とってくる
    @shippings = Shipping.where(customer_id: @customer.id)
    # 商品合計の計算
    @total_price = 0
    @items.each do |cart_item|
      @total_price += cart_item.product.tax_included * cart_item.number
    end

    # shipping_addressの中身を入れる(3はフォームに直接情報入力する為不要)
    if params[:order][:shipping_address] == "0"
      @order.postcode = @customer.postcode
      @order.address = @customer.address
      @order.name = @customer.full_name
    elsif params[:order][:shipping_address] == "1"
      @shipping = Shipping.find_by(id: @order.shipping_id,customer_id: @customer.id)
      @order.postcode = @shipping.postcode
      @order.address = @shipping.address
      @order.name = @shipping.name
    end

    if @order.invalid?
      render 'new'
    end

  end

  def create
    @order = Order.new(order_params)
    @customer = current_customer
    @order.customer_id = @customer.id

    if @order.save
      # アイテムを取り出す
			@items = @customer.cart_items
      @items.each do |cart_item|
      OrderProduct.create(
        product_id: cart_item.product_id,
        order_id: @order.id,
        number: cart_item.number,
        production_status: "着手不可",
        tax_price: cart_item.product.tax_included
      )
      end
      if params[:order][:shipping_address] == "2"
        Shipping.create(
        customer_id: @customer.id,
        name: @order.name,
        postcode: @order.postcode,
        address: @order.address
        )
      end

      redirect_to thanks_orders_path
    else
      render 'confirm'
    end
  end

  def thanks
    @customer = current_customer
    @items = @customer.cart_items
    @items.destroy_all
  end


  def index
      @orders = current_customer.orders
  end

  def show
      @order = Order.find(params[:id])
  end


  private

  def order_params
    params.require(:order).permit(:total_price, :name, :postcode, :address, :pay_method, :shipping_id )
  end


end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController
  
  # 商品情報が必要なメソッドは、先に指定IDの商品を取得していく。
  before_action :set_product, only: [:show]
    
  def index
    # 有効ジャンルを全て取得
    @genres = Genre.where(is_active: true).all
    if params[:genre_id]
      # ジャンル検索の場合、ジャンルが有効であるかつ検索ジャンルに当てはまる商品を取得
      @products = Product.eager_load(:genre).where(genres: {is_active: true}, genre_id: params[:genre_id]).page(params[:page]).per(8)
      # 検索ジャンルの取得
      @genre = Genre.find(params[:genre_id])
    else
      # 商品全表示の場合、ジャンルが有効である商品を全て取得する
      @products = Product.eager_load(:genre).where(genres: {is_active: true}).all.page(params[:page]).per(8)
    end
  end
  
  def show
    # 有効ジャンルを全て取得
    @genres = Genre.where(is_active: true).all
    # カート用の新規のインスタンス変数を定義
    @cart_item = CartItem.new
  end
  
  private
  # ストロングパラメータ
  def product_params
    params.require(:product).permit(:name, :image, :explanation,
       :genre_id, :after_tax_price, :is_sale)
  end
  
  # 指定IDの商品情報の取得
  def set_product
    # IDに基づく商品を取得
    @product = Product.find(params[:id])
  end
  
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customer/shippings_controller.rb
class Customer::ShippingsController < ApplicationController
  
  # ログイン中のユーザのみアクセス許可
  before_action :authenticate_customer!

  def index
    @shippings = Shipping.all
    @shipping = Shipping.new
    @shippings =current_customer.shippings
  end

  def create
    @shipping = Shipping.new(shipping_params)
    if @shipping.save
      flash[:notice] = "配送先情報を登録しました。"
      redirect_to shippings_path
    else
      @shippings = Shipping.all
      render "index"
    end
  end

  def destroy
     @shipping =Shipping.find(params[:id])
     @shipping.destroy
     flash[:notice] = "配送先情報を削除しました。"
     redirect_to shippings_path
  end

  def edit
    @shipping =Shipping.find(params[:id])
  end

  def update
    @shipping =Shipping.find(params[:id])
    if @shipping.update(shipping_params)
      flash[:notice] = "配送先情報を更新しました。"
      redirect_to shippings_path
    else
      render "edit"
    end
  end

private

  def shipping_params
    params.require(:shipping).permit(:postcode,:address,:name).merge(customer_id: current_customer.id)
  end


end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/customer/orders/confirm.html.erb
<%= render 'customer/customer_header' %>

<%= form_with model: @order, url: orders_path, merhod: :post, local: true do |f|%>
<%= f.hidden_field :postcode %>
<%= f.hidden_field :address %>
<%= f.hidden_field :name %>
<%= f.hidden_field :pay_method %>
<%= f.hidden_field :total_price, :value => 800 + @total_price.to_i %>
<%= f.hidden_field :shipping_address, :value => params[:order][:shipping_address] %>

<div class="container">

  <h2 class="title">注文情報確認</h2>

  <div class="row">
    <div class="col-xs-7">
      <!--カートの中の商品を表示する-->
      <table class="table table-bordered">
        <thead>
          <tr class ="bg-primary">
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
          <tr>
            <td><%= attachment_image_tag(item.product, :image, :fill, 36, 25, fallback: "no_image.jpg", class: "order-image image" ) %><%= item.product.name %></td>
            <td><%= item.product.tax_included.to_s(:delimited) %></td>
            <td><%= item.number %></td>
            <td><%= (item.product.tax_included * item.number).to_s(:delimited) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <!--空白-->
    <div class="col-xs-1"></div>

    <div class="col-xs-3">
    <!--その他金額-->
      <table class="table table-bordered">
        <tr>
          <th class ="bg-primary">送料</th>
          <td> 800</td>
        </tr>
        <tr>
          <th class ="bg-primary">商品合計</th>
          <td><%= @total_price.to_s(:delimited) %></td>
        </tr>
        <tr>
          <th class ="bg-primary">請求金額</th>
          <td><%= (800 + @total_price).to_s(:delimited) %></td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12", style="font-size: 18px;">
      <label>支払方法</label>
      <p><%= @order.pay_method %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12", style="font-size: 18px;">
      <label>お届け先</label>
      <p><%= @order.postcode %>&nbsp;<%= @order.address %></br>
        <%= @order.name %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-2 col-xs-offset-5", style="margin-bottom: 30px;">
      <%= f.submit '購入を確定する', class:"btn btn-success btn-lg" %>
    </div>
  </div>

  <% end %>

</div>

<%= render 'customer/footer' %>

app/views/customer/orders/index.html.erb
<%= render 'customer/customer_header' %>
<div class="container">
  <div class= "row">
  <h2 class = "title">注文履歴一覧</h2>
      <!--注文履歴一覧画面 -->
    <div class="col-xs-14">
      <table class="table table-bordered">
        <!--注文履歴一覧画面 一段目-->
        <thead class="thead bg-primary">
          <tr>
            <th class="col-xs-2">注文日</th>
            <th class="col-xs-4">配送先</th>
            <th class="col-xs-2">注文商品</th>
            <th>支払金額</th>
            <th>ステータス</th>
            <th>注文詳細</th>
          <tr>
        </thead>
        <!--注文履歴一覧画面 二段目以降-->
        <tbody>
          <% @orders.each do |order| %>
      <tr>
        <td><%= order.created_at.strftime('%Y/%m/%d')%></td>
        <td>
          <%= order.postcode%><br/>
          <%= order.address%><br/>
          <%= order.name%>
        </td>
        <td>
         <%= order.order_products.map{|order_product| order_product.product.name}.join('<br>').html_safe %>
          </td>
        <td><%= order.total_price.to_s(:delimited)%>円</td>
        <td><%= order.order_status%></td>
        <td>
           <%= link_to '表示する', order_path(order), class: "btn btn-primary" %>
        </td>
       </tr>
          <% end %>
       </tbody>
     </table>
   </div>




  </div>
</div>
 <%= render "customer/footer"%>

app/views/customer/orders/new.html.erb
<%= render 'customer/customer_header' %>

<div class="container" >
  <div class="row">
    <div class="col-xs-12">

      <%= form_with model: @order, url: confirm_orders_path, local: true do |f| %>

      <!--エラーメッセージ-->
      <%= render 'layouts/errors', obj: @order %>

      <h2 class="title">注文情報入力</h2>

      <!--支払方法-->
      <div class="row form-group">
        <label class="strong", style="font-size: 20px;" >支払方法</label></br>
        <div class="box", style="font-size: 18px; padding-left: 30px;">
          <%= f.radio_button :pay_method, "クレジットカード", checked: true, style: "width:20px; height: 20px;" %>&nbsp;クレジットカード</br>
          <%= f.radio_button :pay_method, "銀行振込", style: "width:20px; height: 20px;" %>&nbsp;銀行振込
        </div>
      </div>

      <!--お届け先-->
      <div class="row form-group">
        <label class="strong", style="font-size: 20px; ">お届け先</label></br>
        <!--①会員登録の住所を選択-->
        <div class="box", style="font-size: 18px; padding-left: 30px;">
          <%= f.radio_button :shipping_address, "0", checked: true, style: "width:20px; height: 20px;" %>&nbsp;現在のご住所
          <div class="address",  style="padding-left: 30px;">
            <%= @customer.postcode %> <%= @customer.address %></br>
            <%= @customer.full_name %>
          </div>
        </div>
      </div>

      <!--②配送先の住所から選択-->

      <div class="row form-group">
        <!--配送先が0じゃなかったら？-->
        <div class="box", style="font-size: 18px; padding-left: 30px;">
          <% if @shippings.count != 0 %>
          <%= f.radio_button :shipping_address, "1", style: "width:20px; height: 20px;" %>&nbsp;登録済み住所から選択</br>
          <div class="col-xs-10", style="padding-left: 30px;">
              <!--↓参照先id,変数,何番目をとってきたかのid,選択肢-->
              <%= f.collection_select :shipping_id, @shippings, :id, :full_address, {},{ class: "form-control"}%>
            </div>
          <% else %>
            <%= f.radio_button :shipping_address, "1", style: "width:20px; height: 20px;", disabled: true %>&nbsp;登録済み住所から選択</br>
            <div class="col-xs-10", style="padding-left: 30px;">
            <p class="memo" style="color: red;">配送先が登録されていません</p>
            </div>
          <% end %>
        </div>
      </div>

      <!--③今回限りの配送先を入力-->
      <div class="row form-group">
        <div class="box", style="font-size: 18px; padding-left: 30px;">
          <%= f.radio_button :shipping_address, "2", style: "width:20px; height: 20px;" %>&nbsp;新しいお届け先
        </div>
        <div class="row field", style="padding-left: 50px;">
          <p class="col-xs-3 control-label">郵便番号（ハイフンなし）</p>
          <div class="col-xs-3">
            <%= f.text_field :postcode, class:"form-control" %>
          </div>
        </div>
        <div class="row field", style="padding-left: 50px;">
          <p class="col-xs-3 control-label">住所</p>
          <div class="col-xs-5">
            <%= f.text_field :address, class: "form-control" %>
          </div>
        </div>
        <div class="row field", style="padding-left: 50px;">
          <p class="col-xs-3 control-label">宛名</p>
          <div class="col-xs-3">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>
      </div>

      <!--ボタン-->
      <div class="col-xs-2 col-xs-offset-5", style="margin-bottom: 30px;">
        <%= f.submit '確認画面へ進む', class:"btn btn-primary btn-lg" %>
      </div>
      <% end %>

    </div>
  </div>
</div>

<%= render 'customer/footer' %>

app/views/customer/orders/show.html.erb
<%= render "customer/customer_header"%>
<div class="container">
  <div class="row">
     <div class="col-xs-12" style="margin-top: 30px;">
       <h2 class= "title" >注文履歴詳細</h2>
     </div>
  <form class ="form-inline">
   <div class="col-xs-6">
   <p><strong>注文情報</strong></p>
      <table class= "table table-bordered col-xs-1" style="margin-top:5px;">
        <tr>
          <th class="bg-primary col-xs-4">注文日</th><td><%= @order.created_at.strftime('%Y/%m/%d')%></td>
        </tr>
        <tr>
          <th class="bg-primary col-xs-4 ">配送先</th><td><%=@order.postcode%></br><%= @order.address %><br/><%= @order.name%></td>
        </tr>
        <tr>
          <th class="bg-primary col-xs-4">支払方法</th><td><%=@order.pay_method  %></td>
        </tr>
        <tr>
          <th class="bg-primary col-xs-4">ステータス</th><td><%= @order.order_status %></td>
        </tr>
      </table>
  </div>
  <div class="col-xs-4">
    <p><strong>請求情報</strong></p>
      <table class= "table table-bordered col-xs-1" style="margin-top:5px;">
        <tr>
          <th class="bg-primary col-xs-4">商品合計</th><td><%= (@order.total_price - @order.postage).to_s(:delimited)%></td>
        </tr>
        <tr>
          <th class="aline-middle bg-primary col-xs-4 ">配送料</th><td><%= @order.postage.to_s(:delimited)%></td>
        </tr>
        <tr>
          <th class="bg-primary col-xs-4">ご請求額</th><td><strong><%= @order.total_price.to_s(:delimited) %></strong></td>
        </tr>
      </table>
  </div>
 </form>
<div class="col-xs-8">
   <p><strong>注文内容</strong></p>
      <table class="table table-bordered">
        <!--注文履歴一覧画面 一段目-->
        <thead class="thead bg-primary">
          <tr>
            <th class="col-xs-7">商品</th>
            <th class="col-xs-2">単価（税込み）</th>
            <th>個数</th>
            <th>小計</th>
          </tr>
        </thead>
        <!--注文履歴一覧画面 二段目以降-->
        <tbody>
        <%@order.order_products.each do |order_product|%>
      <tr>
        <td><%= order_product.product.name %></td>
        <td><%= order_product.tax_price.to_s(:delimited) %></td>
        <td><%= order_product.number%></td>
        <td><%= order_product.subtotal_price.to_s(:delimited)%></td>
       </tr>
       <% end %>
       </tbody>
     </table>
     <p><%=link_to "注文一覧へ戻る", orders_path,class: "btn btn-primary"%></p>
   </div>
  </div>
</div>
<%= render "customer/footer"%>

app/views/customer/orders/thanks.html.erb
<%= render 'customer/customer_header' %>

<!--ありがとうメッセージ-->
<div class="text-center", style="margin: 300px 0 300px 0 ;">
  <p class="lead">ご購入ありがとうございました！</p>
</div>


<%= render 'customer/footer' %>