config/routes.rb
Rails.application.routes.draw do

  # ルートパスを会員TOPページに設定
  root 'customer/homes#top'
  # 会員TOPページ
  get '/admin' => 'admin/homes#top'
  # 会員紹介ページ
  get '/about' => 'customer/homes#about', as: 'about'


  
  devise_for :customers,skip: :all
  devise_scope :customer do
    #サインアップ
    get 'customers/sign_up' =>'customers/registrations#new', as: :new_customer_registration
    post 'customers'=>'customers/registrations#create', as: :customer_registration
    #ログイン、ログアウト
    get 'customers/sign_in'=>'customers/sessions#new',as: :new_customer_session
    post 'customers/sign_in'=>'customers/sessions#create',as: :customer_session
    delete 'customers/sign_out' =>'customers/sessions#destroy', as: :destroy_customer_session
  end
  
  # 管理者ログイン画面のルーティング
  # セッションパス修正admin→admins
  # devise_for :admins, controllers: {
  #   sessions: 'admins/sessions'
  # }
  
  devise_for :admins,skip: :all
  devise_scope :admin do
    #ログイン、ログアウト
    get 'admins/sign_in'=>'admins/sessions#new',as: :new_admin_session
    post 'admins/sign_in'=>'admins/sessions#create',as: :admin_session
    delete 'admins/sign_out' =>'admins/sessions#destroy', as: :destroy_admin_session
  end
  

  # 管理者側の各機能のルーティング
  # namespaseでURLとコントローラのパスの頭に「/admin」が入るようにする
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :products, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :order_products, only: [:update]
    get '/search' => 'searchs#search', as: 'search'
  end

  # 会員側のルーティング
  # scope moduleでコントローラのパスのみ頭に「/customer」が入るようにする
  scope module: :customer do
    # 今回は他会員の情報を利用しないため、resource(単数形)にすることでURLに:idを含めないようにする
    resource :customers, only: [:show,:edit,:update] do
      # RESTfulなURL以外は個別にcollectionで設定する
      collection do
        # URLとコントローラアクション名が一致しない場合のみ、個別にコントローラのパスを指定する
        get 'withdrawal' => 'customers#withdrawal_show'
        patch 'withdrawal'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      # RESTfulなURL以外は個別にcollectionで設定する
      collection do
        post 'confirm'
        get 'thanks'
      end
    end
    resources :products, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      # RESTfulなURL以外は個別にcollectionで設定する
      collection do
        # URLとコントローラアクション名が一致しない場合のみ、個別にコントローラのパスを指定する
        delete '' => 'cart_items#destroy_all'
      end
    end
    resources :shippings, only: [:index, :edit, :create, :update, :destroy]
    resources :order_products, only: [:update]
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer, optional: true
  has_many :order_products, dependent: :destroy

  #カラムとして存在しないものをメソッドとして定義する
  attr_accessor :shipping_id

  # バリデーション
  validates :postcode, presence: true, length: { is: 7 }, format: { with: /\A[0-9]+\z/ }
  validates :address, presence: true
  validates :name, presence: true


  # ENUMの設定
  enum pay_method: { "クレジットカード": 0, "銀行振込": 1 }
  enum order_status: {"入金待ち":0, "入金確認":1, "製作中":2, "発送準備中":3, "発送済み":4 }

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    
    # ログイン中の管理者のみアクセス許可
    before_action :authenticate_admin!
    
    def index
        if params[:only_today_flag]
            now = Time.current
            # 本日の注文情報のみ取得
            @orders = Order.where(created_at: now.all_day).page(params[:page]).per(10)
            
        elsif params[:customer_id]
            # 指定のユーザーの注文情報のみ取得
            @orders = Order.where(customer_id: params[:customer_id]).page(params[:page]).per(10)
            
        else
            # 全注文情報を取得する
            @orders = Order.all.page(params[:page]).per(10)
        end
    end
    
    def show
        # 指定の注文を取得
        @order = Order.find(params[:id])
    end
    
    def update
        # 指定の注文を取得
        @order = Order.find(params[:id])
        if @order.update(order_params)
            
            # 注文ステータスが「入金確認」となった場合、注文商品の製作ステータスを全て「製作待ち」にする
            if (@order.order_status == "入金確認")
                @order.order_products.each do |order_product|
                    order_product.update(production_status: "製作待ち")
                end
            end
            
            flash[:notice] = "注文ステータスを変更しました。"
            redirect_to admin_order_path(@order)
        else
            render :show
        end
    end
    
    # ストロングパラメータ
    private
	def order_params
		  params.require(:order).permit(:order_status)
	end
    
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController

  # ログイン中のユーザのみアクセス許可
  before_action :authenticate_customer!

  def new
    # 表示用
    @customer = current_customer
    # 新規注文用の箱
    @order = Order.new(customer_id: @customer.id)
    # 自分のIDの配送先を全部とってくる
    @shippings = Shipping.where(customer_id: @customer.id)
  end

  def confirm
    # 新規注文用の箱
    @order = Order.new(order_params)
    # 表示用
    @customer = current_customer
    # カートの中身をインスタンス変数に入れる
    @items = @customer.cart_items
    # 自分のIDの配送先を全部とってくる
    @shippings = Shipping.where(customer_id: @customer.id)
    # 商品合計の計算
    @total_price = 0
    @items.each do |cart_item|
      @total_price += cart_item.product.tax_included * cart_item.number
    end

    # shipping_addressの中身を入れる(3はフォームに直接情報入力する為不要)
    if params[:order][:shipping_address] == "0"
      @order.postcode = @customer.postcode
      @order.address = @customer.address
      @order.name = @customer.full_name
    elsif params[:order][:shipping_address] == "1"
      @shipping = Shipping.find_by(id: @order.shipping_id,customer_id: @customer.id)
      @order.postcode = @shipping.postcode
      @order.address = @shipping.address
      @order.name = @shipping.name
    end

    if @order.invalid?
      render 'new'
    end

  end

  def create
    @order = Order.new(order_params)
    @customer = current_customer
    @order.customer_id = @customer.id

    if @order.save
      # アイテムを取り出す
			@items = @customer.cart_items
      @items.each do |cart_item|
      OrderProduct.create(
        product_id: cart_item.product_id,
        order_id: @order.id,
        number: cart_item.number,
        production_status: "着手不可",
        tax_price: cart_item.product.tax_included
      )
      end
      if params[:order][:shipping_address] == "2"
        Shipping.create(
        customer_id: @customer.id,
        name: @order.name,
        postcode: @order.postcode,
        address: @order.address
        )
      end

      redirect_to thanks_orders_path
    else
      render 'confirm'
    end
  end

  def thanks
    @customer = current_customer
    @items = @customer.cart_items
    @items.destroy_all
  end


  def index
      @orders = current_customer.orders
  end

  def show
      @order = Order.find(params[:id])
  end


  private

  def order_params
    params.require(:order).permit(:total_price, :name, :postcode, :address, :pay_method, :shipping_id )
  end


end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<%= render 'admin/admin_header' %>
<div class="container">
  
  <h2 class="title">注文履歴一覧</h2>
  <div class="row">
	  <!--注文履歴一覧 -->
		<div class="col-xs-10 col-xs-offset-1">
      <table class="table">
        <!--注文一覧 テーブルヘッダー-->
        <thead class="thead bg-primary">
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
	        
	      <!--注文履歴一覧 テーブルボディ-->
        <tbody class ="tbody bg-default">
          <% @orders.each do |order| %>
            <tr>
			        <td><%= link_to (l order.created_at), admin_order_path(order), class: "link" %></td>
			        <td><%= order.customer.full_name %></td>
			        <td><%= order.order_products.sum { |hash| hash[:number]} %></td>
			        <td><%= order.order_status %></td>
		       	</tr>
	        <% end %>
	      </tbody>
      </table>
    <div class="text-center"><%= paginate(@orders) %></div>
		</div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<%= render 'admin/admin_header' %>
<div class="container">
  <!--サクセスメッセージ-->
  <% if flash[:notice] %>
    <p class="alert alert-success"><%= flash[:notice] %></p>
  <% end %>
  <h2 class="title">注文履歴詳細</h2>
  <div class="row">
    <div class="row form-group" >
      <label class="col-xs-2 control-label" >購入者</label>
      <div class="col-xs-9">
        <%= link_to @order.customer.full_name, admin_customer_path(@order.customer.id), class: "link" %>
      </div>
    </div>

    <div class="row form-group" >
      <label class="col-xs-2 control-label" >配送先</label>
      <div class="col-xs-9">
        〒<%= @order.postcode %>&nbsp;&nbsp;<%= @order.address %></br>
        <%= @order.name %>
      </div>
    </div>
    
    <div class="row form-group" >
      <label class="col-xs-2 control-label" >支払方法</label>
      <div class="col-xs-9">
        <%= @order.pay_method %>
      </div>
    </div>
    
    <div class="row form-group" >
      <label class="col-xs-2 control-label" >注文ステータス</label>
      <%= form_with model: @order, url: admin_order_path(@order), method: :patch, local: true do |f| %> 
        <div class="col-xs-2">
          <%= f.select :order_status, Order.order_statuses.keys, {}, {class: "form-control"} %>
        </div>
        <div class="col-xs-2">
          <%= f.submit "更新", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
    
  </div>
  
  <div class="row total-price-area top-space">
    <div class="col-xs-8">
      <table class="table table-default">
      	<!--注文商品一覧 テーブルヘッダー-->
      	<thead class="thead bg-primary">
        	<tr>
  	        <th class="col-xs-4">商品名</th>
  	        <th class="col-xs-2">単価（税込）</th>
  	        <th class="col-xs-1">数量</th>
  	        <th class="col-xs-1">小計</th>
  	        <th class="col-xs-4">製作ステータス</th>
        	</tr>
        </thead>
          
        <!--注文商品一覧 テーブルボディ-->
        <tbody class ="tbody bg-default">
          <% @order.order_products.each do |order_product| %>
  	        <tr>
  		        <td><%= order_product.product.name %></td>
  		        <td><%= order_product.tax_price %></td>
  		        <td><%= order_product.number %></td>
  		        <td><%= (order_product.tax_price * order_product.number).to_s(:delimited) %></td>
		          <td align="center">
		            <%= form_with model: order_product, url: admin_order_product_path(order_product), method: :patch, local: true, class: "form-inline" do |f| %> 
  		            <%= f.select :production_status, OrderProduct.production_statuses.keys,{},{ class: "form-control"} %>
  					      <%= f.submit "更新", class: "btn btn-primary" %>
					      <% end %>
						  </td>
  	       	</tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-xs-offset-1 col-xs-3">
      
      <div class="row form-group" >
        <label class="col-xs-6 control-label" >商品合計</label>
        <div class="col-xs-6">
          <p><%= (@order.total_price - @order.postage).to_s(:delimited) %>円</p>
        </div>
      </div>
      
      <div class="row form-group" >
        <label class="col-xs-6 control-label" >送料</label>
        <div class="col-xs-6">
          <p><%= @order.postage.to_s(:delimited) %>円</p>
        </div>
      </div>
      
      <div class="row form-group" >
        <label class="col-xs-6 control-label" >請求額合計</label>
        <div class="col-xs-6">
          <label><%= @order.total_price.to_s(:delimited) %>円</label>
        </div>
      </div>
      
    </div>
  </div>
</div>