config/routes.rb
Rails.application.routes.draw do

  # ルートパスを会員TOPページに設定
  root 'customer/homes#top'
  # 会員TOPページ
  get '/admin' => 'admin/homes#top'
  # 会員紹介ページ
  get '/about' => 'customer/homes#about', as: 'about'


  
  devise_for :customers,skip: :all
  devise_scope :customer do
    #サインアップ
    get 'customers/sign_up' =>'customers/registrations#new', as: :new_customer_registration
    post 'customers'=>'customers/registrations#create', as: :customer_registration
    #ログイン、ログアウト
    get 'customers/sign_in'=>'customers/sessions#new',as: :new_customer_session
    post 'customers/sign_in'=>'customers/sessions#create',as: :customer_session
    delete 'customers/sign_out' =>'customers/sessions#destroy', as: :destroy_customer_session
  end
  
  # 管理者ログイン画面のルーティング
  # セッションパス修正admin→admins
  # devise_for :admins, controllers: {
  #   sessions: 'admins/sessions'
  # }
  
  devise_for :admins,skip: :all
  devise_scope :admin do
    #ログイン、ログアウト
    get 'admins/sign_in'=>'admins/sessions#new',as: :new_admin_session
    post 'admins/sign_in'=>'admins/sessions#create',as: :admin_session
    delete 'admins/sign_out' =>'admins/sessions#destroy', as: :destroy_admin_session
  end
  

  # 管理者側の各機能のルーティング
  # namespaseでURLとコントローラのパスの頭に「/admin」が入るようにする
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :products, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :order_products, only: [:update]
    get '/search' => 'searchs#search', as: 'search'
  end

  # 会員側のルーティング
  # scope moduleでコントローラのパスのみ頭に「/customer」が入るようにする
  scope module: :customer do
    # 今回は他会員の情報を利用しないため、resource(単数形)にすることでURLに:idを含めないようにする
    resource :customers, only: [:show,:edit,:update] do
      # RESTfulなURL以外は個別にcollectionで設定する
      collection do
        # URLとコントローラアクション名が一致しない場合のみ、個別にコントローラのパスを指定する
        get 'withdrawal' => 'customers#withdrawal_show'
        patch 'withdrawal'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      # RESTfulなURL以外は個別にcollectionで設定する
      collection do
        post 'confirm'
        get 'thanks'
      end
    end
    resources :products, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      # RESTfulなURL以外は個別にcollectionで設定する
      collection do
        # URLとコントローラアクション名が一致しない場合のみ、個別にコントローラのパスを指定する
        delete '' => 'cart_items#destroy_all'
      end
    end
    resources :shippings, only: [:index, :edit, :create, :update, :destroy]
    resources :order_products, only: [:update]
  end

end

app/models/product.rb
class Product < ApplicationRecord
  
  # 多重度の設定
  belongs_to :genre, optional: true  
  has_many :cart_items
  has_many :order_products
  
 
  # 画像を設定できるようにする
  attachment :image, destroy: false
  
  # バリデーションチェック
  # 空白時にエラー
  validates :name, :explanation, :genre_id, :after_tax_price, :image, presence: true
  # 数値以外が入力された場合はエラー
  validates :after_tax_price, numericality: { only_integer: true }
  # is_saleの値がtrue,false以外の場合はエラー
  validates :is_sale, inclusion: [true, false]
  
  # 商品の税込価格の計算メソッド
  def tax_included
  	(after_tax_price * 1.1).round
  end
    
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  
  # ログイン中の管理者のみアクセス許可
  before_action :authenticate_admin!
  
  # 商品情報が必要なメソッドは、先に指定IDの商品を取得していく。
  before_action :set_product, only: [:show, :edit, :update]
  # ジャンルの取得が必要なメソッドでは、先にジャンルを取得しておく
  before_action :set_genres, only: [:new, :edit, :index, :create, :update]
  
  def index
    # ジャンルが有効である商品を全て取得する。1ページ10個表示する。
    @products = Product.eager_load(:genre).where(genres: {is_active: true}).all.page(params[:page]).per(10)
  end
  
  def new
    # 新規商品用のインスタンス変数
    @product = Product.new
  end
  
  def show
  end
  
  def edit
  end
  
  def create
    # 新規商品情報の取得
    @product = Product.new(product_params)
    # 新規商品情報の保存
    if @product.save
      flash[:notice] = "新商品を登録しました。"
      redirect_to admin_product_path(@product)
    else
      # エラーが発生した場合
      render :new
    end
  end
  
  def update
    if @product.update(product_params)
      flash[:notice] = "商品内容を変更しました。"
      redirect_to admin_product_path(@product)
    else
      render :edit
    end
  end
  
  
  private
  # ストロングパラメータ
  def product_params
    params.require(:product).permit(:name, :image, :explanation,
       :genre_id, :after_tax_price, :is_sale)
  end  
  
  # 指定IDの商品情報の取得
  def set_product
    # IDに基づく商品を取得
    @product = Product.find(params[:id])
  end
  
  # 有効ジャンルの取得
  def set_genres
    @genres = Genre.where(is_active: true)
  end
  
end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController
  
  # 商品情報が必要なメソッドは、先に指定IDの商品を取得していく。
  before_action :set_product, only: [:show]
    
  def index
    # 有効ジャンルを全て取得
    @genres = Genre.where(is_active: true).all
    if params[:genre_id]
      # ジャンル検索の場合、ジャンルが有効であるかつ検索ジャンルに当てはまる商品を取得
      @products = Product.eager_load(:genre).where(genres: {is_active: true}, genre_id: params[:genre_id]).page(params[:page]).per(8)
      # 検索ジャンルの取得
      @genre = Genre.find(params[:genre_id])
    else
      # 商品全表示の場合、ジャンルが有効である商品を全て取得する
      @products = Product.eager_load(:genre).where(genres: {is_active: true}).all.page(params[:page]).per(8)
    end
  end
  
  def show
    # 有効ジャンルを全て取得
    @genres = Genre.where(is_active: true).all
    # カート用の新規のインスタンス変数を定義
    @cart_item = CartItem.new
  end
  
  private
  # ストロングパラメータ
  def product_params
    params.require(:product).permit(:name, :image, :explanation,
       :genre_id, :after_tax_price, :is_sale)
  end
  
  # 指定IDの商品情報の取得
  def set_product
    # IDに基づく商品を取得
    @product = Product.find(params[:id])
  end
  
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/customer/products_helper.rb
module Customer::ProductsHelper
end

app/views/admin/products/_product_form.html.erb
<div class="row form-group">
  <%= f.label "商品名", class: "col-sm-3 control-label" %>
  <div class="col-sm-4">
	  <%= f.text_field :name, class: "form-control" %>
  </div>
</div>

<div class="row form-group">
	<%= f.label "商品説明", class: "col-sm-3 control-label" %>
	<div class="col-sm-4">
	  <%= f.text_area :explanation, class: "form-control" %>
  </div>
</div>

<div class="row form-group">
	<%= f.label "ジャンル", class: "col-sm-3 control-label" %>
	<div class="col-sm-4">
	  <%= f.collection_select :genre_id, @genres, :id, :name, { prompt: "-- 選択してください --" }, { class: "form-control" } %>
  </div>
</div>

<div class="row form-group">
	<%= f.label "税別価格", class: "col-sm-3 control-label" %>
	<div class="col-sm-4">
	  <%= f.text_field :after_tax_price, class: "form-control" %>
  </div>
  円
</div>

<div class="row form-group">
	<%= f.label "販売ステータス", class: "col-sm-3 control-label" %>
	<div class="col-sm-4">
	  <%= f.select :is_sale, [["販売中",true],["売切れ",false]], {include_blank: '--選択してください--'}, {class: "form-control"} %>
  </div>
</div>

app/views/admin/products/edit.html.erb
<%= render 'admin/admin_header' %>
<div class="container">
  <!-- エラーメッセージ表示-->
  <%= render "layouts/errors", obj: @product %>
  <h2 class="title">商品編集</h2>
  <div class="row">

    <!-- 商品の編集フォーム -->
    <%= form_with model: @product, url: admin_product_path, method: :patch, local: true do |f| %>

    	<div class="col-xs-4">
  	    <!--ここから　商品画像のプレビューは余裕があればAjaxで実装-->
  	    <div class="img_field">
          <%= attachment_image_tag(@product, :image, :fill, 300, 220, fallback: "no_image.jpg", class:"img-responsive img-thumbnail product-image" ) %>
        </div>
  	    <!--ここまで　商品画像のプレビューは余裕があればAjaxで実装-->
      	<div class="field">
      		<%= f.attachment_field :image %>
      	</div>
      </div>
      
      <div class="col-xs-8">
        <!--商品情報入力フォームの部分テンプレート呼び出し-->
        <%= render "product_form", f: f %>
      	
      	<div class="actions col-xs-9">
  	      <%= f.submit "変更を保存", class: "btn btn-primary btn-lg pull-right" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/products/index.html.erb
<%= render 'admin/admin_header' %>
<div class="container">
	<!--検索結果がない場合のメッセージ-->
  <% if flash[:alert] %>
    <p class="alert alert-danger"><%= flash[:alert] %></p>
  <% end %>
  <h2 class="title">商品一覧</h2>
  <div class="row">
	  <!--商品一覧 -->
		<div class="col-xs-10 col-xs-offset-1">
			<!--商品新規登録アイコン-->
		  <%= link_to new_admin_product_path do %>
		  	<i class="fas fa-plus-circle fa-3x col-xs-1 col-xs-offset-11 mb-4"></i>
		  <% end %>
			
	    <table class="table">
	    	<!--商品一覧 テーブルヘッダー-->
	    	<thead class="thead bg-primary">
	      	<tr>
		        <th>商品ID</th>
		        <th>商品名</th>
		        <th>税抜価格</th>
		        <th>ジャンル</th>
		        <th>ステータス</th>
	      	<tr>
	      <thead>
	        
	      <!--商品一覧 テーブルボディ-->
	      <tbody class ="tbody bg-default">
	        <% @products.each do |product| %>
		        <tr>
			        <td><%= product.id%></td>
			        <td><%= link_to product.name, admin_product_path(product), class: "link" %></td>
			        <td><%= (product.after_tax_price).to_s(:delimited) %></td>
			        <td><%= product.genre.name %></td>
			        <td>
			        	<% if product.is_sale == true %>
								　販売中
								<% elsif product.is_sale == false %>
								　売切れ
								<% end %>
							</td>
		       	<tr>
	        <% end %>
	      </tbody>
	   </table>
	  <div class="text-center"><%= paginate(@products) %></div>
		</div>
  </div>
</div>

app/views/admin/products/new.html.erb
<%= render 'admin/admin_header' %>
<div class="container">
  <!-- エラーメッセージ表示-->
  <%= render "layouts/errors", obj: @product %>
  <h2 class="title">商品新規登録</h2>
  <div class="row">

    <!-- 商品の新規登録フォーム -->
    <%= form_with model: @product, url: admin_products_path, method: :post, local: true do |f| %>

    	<div class="col-xs-4">
  	    <!--ここから　商品画像のプレビューは余裕があればAjaxで実装-->
  	    <div class="img_field">
          <%= attachment_image_tag(@product, :image, :fill, 300, 220, fallback: "no_image.jpg", class:"img-responsive img-thumbnail product-image" ) %>
        </div>
        
  	    <!--ここまで　商品画像のプレビューは余裕があればAjaxで実装-->
      	<div class="field">
      		<%= f.attachment_field :image %>
      	</div>
      </div>
      
      <div class="col-xs-8">
        <!--商品情報入力フォームの部分テンプレート呼び出し-->
        <%= render "product_form",f: f %>
      	
      	<div class="actions col-xs-9">
  	      <%= f.submit "新規登録", class: "btn btn-primary btn-lg pull-right" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/products/show.html.erb
<%= render 'admin/admin_header' %>
<div class="container">
  <!--サクセスメッセージ-->
  <% if flash[:notice] %>
    <p class="alert alert-success"><%= flash[:notice] %></p>
  <% end %>
  <h2 class="title">商品詳細</h2>
  <div class="row">
    
    <!--商品画像の表示-->
    <div class="col-xs-4">
	    <%= attachment_image_tag(@product, :image, :fill, 300, 220, fallback: "no_image.jpg", class:"img-responsive img-thumbnail product-image" ) %>
  	</div>
    
    <!--商品情報の表示-->
    <div class="col-xs-8">
        <!--商品名-->
        <div class="row form-group">
  				<strong class="col-sm-3 control-label">商品名</strong>
  				<span class="col-sm-4 control-label"><%= @product.name %></span>
				</div></br>
        <!--商品説明-->
        <div class="row form-group">
          <strong class="col-sm-3 control-label">商品説明</strong>
  				<span class="col-sm-4 control-label"><%= @product.explanation %></span></br>
        </div></br>
        <!--ジャンル-->
        <div class="row form-group">
          <strong class="col-sm-3 control-label">ジャンル</strong>
  				<span class="col-sm-4 control-label"><%= @product.genre.name %></span></br>
        </div></br>
        <!--価格-->
        <div class="row form-group">
          <strong class="col-sm-3 control-label">税込価格（税別価格）</strong>
  				<span class="col-sm-6 control-label"><%= @product.tax_included.to_s(:delimited) %>（<%= @product.after_tax_price.to_s(:delimited) %>）円</span></br>
        </div></br>
        <!--販売ステータス-->
        <div class="row form-group">
          <strong class="col-sm-3 control-label">販売ステータス</strong>
  				<span class="col-sm-4 control-label">
    				<% if @product.is_sale == true %>
              販売中
  					<% elsif @product.is_sale == false %>
              売切れ
  					<% end %>
  				</span></br>
        </div></br>
        <!--編集ボタン-->
        <div class="actions col-xs-9">
  	      <%= link_to "編集する", edit_admin_product_path(@product), class: "btn btn-primary btn-lg pull-right" %>
        </div>
    </div>
    
  </div>
</div>